let the remove script handle multiple arguments

diff --git a/grm b/grm
--- a/grm
+++ b/grm
@@ -65,15 +65,18 @@ grm_new() {
 }
 
 grm_remove() {
-  [ -z "$1" ] && { echo "no repo name given, exiting..."; exit 1; }
+  [ $# -gt 0 ] || { echo "no repo name given, exiting..."; exit 1; }
 
-  printf "remove %s [y/N]? " "$1"
-  read -r resp
-  case "$resp" in
-    [yY]) rm -rf "$repos_root/${1}.git" || \
-      { echo "failed to remove $1"; exit 1; };;
-    *) exit ;;
-  esac
+  for repo in "$@"
+  do
+    printf "remove %s [y/N]? " "$repo"
+    read -r resp
+    case "$resp" in
+      [yY]) rm -rf "$repos_root/$repo.git" || \
+        { echo "failed to remove $repo"; exit 1; };;
+      *) exit ;;
+    esac
+  done
 }
 
 grm_list() {
